<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EmailValidation" Version="1.2.0" />
    <PackageReference Include="FluentResults" Version="3.16.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
	<PropertyGroup>
		<PackageId>Valibute</PackageId>
		<Version>1.0.0</Version>
		<Authors>LainSoftware</Authors>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<RepositoryUrl>https://github.com/LainSoftwareCS/Valibute</RepositoryUrl>
		<Description>Validation library that only uses props attributes!</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
	<ItemGroup>
		<None Include="docs\README.md" />
	</ItemGroup>
</Project>
